Make test harness preserve stderr on error exit

diff --git a/tests/harness b/tests/harness
--- a/tests/harness
+++ b/tests/harness
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-set -e
-
 if [ $# -eq 0 ]
 then
     echo Usage:   $0 TESTDIR '[IMPLEMENTATION CMDLINE...]'
@@ -50,7 +48,9 @@ do
     should_error=$(printf '%s\n' "$testcase" | grep -o _error || true)
     short=$(printf "$testcase" | sed -e 's/_/ /g; s/error/(error)/; s/\.grace$//;')
     printf '%-40s' "${short}"
-    if ! "$@" "$testcase" > _test_data/test.out 2> _test_data/test.err
+    "$@" "$testcase" > _test_data/test.out 2> _test_data/test.err
+    code=$?
+    if [ $code -ne 0 ]
     then
         if [ "$should_error" ]
         then
@@ -59,8 +59,12 @@ do
             passed=$((passed + 1))
         else
             printf '|%sX%s  | ' "$hl" "$nm"
-            echo "exit code $!" > _test_data/"${testcase%.grace}".exit
-            fail "Error exit"
+            echo "exit code $code" > _test_data/"${testcase%.grace}".exit
+            if [ -s _test_data/test.err ]
+            then
+                cp _test_data/test.err _test_data/"${testcase%.grace}".err
+            fi
+            fail "Error exit $code"
             failed=$((failed + 1))
         fi
     elif ! cmp -s _test_data/test.out _test_data/test.expected
