Add tests for inheritance behaviours

diff --git a/tests/harness b/tests/harness
--- a/tests/harness
+++ b/tests/harness
@@ -25,12 +25,19 @@ for testcase in *.grace
 do
     total=$((total + 1))
     grep -o -E '//: .*' "$testcase" | cut -b 5- > _test_data/test.expected
+    should_fail=$(printf '%s\n' "$testcase" | grep -o _fail || true)
     printf '%-40s' "$testcase"
     if ! "$@" "$testcase" > _test_data/test.out 2> _test_data/test.err
     then
-        echo "exit code $!" > _test_data/"${testcase%.grace}".exit
-        echo "FAIL      Error exit"
-        failed=$((failed + 1))
+        if [ "$should_fail" ]
+        then
+            echo "PASS      Expected error"
+            passed=$((passed + 1))
+        else
+            echo "exit code $!" > _test_data/"${testcase%.grace}".exit
+            echo "FAIL      Error exit"
+            failed=$((failed + 1))
+        fi
     elif ! cmp -s _test_data/test.out _test_data/test.expected
     then
         echo "FAIL      Wrong output"
@@ -41,6 +48,10 @@ do
         echo "FAIL      stderr"
         failed=$((failed + 1))
         cp _test_data/test.err _test_data/"${testcase%.grace}".err
+    elif [ "$should_fail" ]
+    then
+        echo "FAIL      Should be error"
+        failed=$((failed + 1))
     else
         echo PASS
         passed=$((passed + 1))
